### PR TITLE
Make gem version badge link to rubygems

### PR DESCRIPTION
**Pull request by PragTob**
Also changed the version badge to the one you get from rubygems, more visually consistent with the other badge but I can change that back if you want to :)

image

### CODE REVIEW

**Comment by PragTob** [comment]
@cla-bot check

**Comment by PragTob** [comment]
But why I signed?!?!

**Comment by wagenet** [comment]
@PragTob sorry, it is not fully automatic!

**Comment by wagenet** [comment]
@cla-bot check

**Pull request merged**
