### PR TITLE
Fix env key [ci skip]

### PR DESCRIPTION
**Pull request by y-yagi**
It seems `SKYLIGHT_ENABLED` is correct.
https://github.com/skylightio/skylight-ruby/blob/v1.5.0/lib/skylight/railtie.rb#L120..L121

### CODE REVIEW

**Comment by y-yagi** [comment]
I signed the CLA.

**Comment by wagenet** [comment]
@y-yagi Thanks! Definitely a typo.

@cla-bot check.

**Comment by wagenet** [comment]
Hmm... Not sure why cla-bot is confused, but I see you in the list.

**Comment by ColinEberhardt** [comment]
Hi @wagenet - if you're having problems with cla-bot, please feel free to give me a shout (I'm the bot author)

**Comment by wagenet** [comment]
@ColinEberhardt thanks for reaching out. I think I made a mistake on our end, but if it turns out to be otherwise, I'll let you know.

**Comment by wagenet** [comment]
@cla-bot check

**Pull request merged**
