### PR TITLE
Tests for Sinatra namespaces

### PR DESCRIPTION
**Pull request by stereobooster**
Looked into https://github.com/skylightio/skylight-ruby/issues/88. Not sure what I missing - based on tests it works, but reports don't display namespaces. Syill investigating

### CODE REVIEW

**Comment by wagenet** [comment]
Thanks! This will be useful when we get a chance to work on implementation :)

**Comment by wagenet** [comment]
@stereobooster thanks for writing these tests. Even though they don't show the failure case that you were trying to prove, it would still be useful to merge them. Can you [sign our CLA](https://docs.google.com/spreadsheet/viewform?usp=drive_web&formkey=dHJVY1M5bzNzY0pwN2dRZjMxV0dXSkE6MA#gid=0)?

**Comment by wagenet** [comment]
@cla-bot check

**Comment by wagenet** [comment]
@cla-bot check

**Comment by stereobooster** [comment]
namespaces are supported, this PR doesn't add much value

**Comment by wagenet** [comment]
@stereobooster did you ever figure out why things weren't showing up correctly for you?

**Comment by stereobooster** [comment]
There was really strange setup, it was more than one Sinatra app mounted with Rack to different endpoints. I used another gem which was reading path info and it was the same issue. I changed setup and everything worked. There is no issue in Skylight. Skylight is perfect 👍 

Side note: do you have plans for distributed tracing support?

**Comment by wagenet** [comment]
@stereobooster we don't currently have plans for distributed tracing support, but it's something we're thinking about. If you could reach out with the in-app messenger or via support@skylight.io that would be great.

**Pull request closed without merging**
