### PR TITLE
Normalizer for couch_potato

### PR DESCRIPTION
**Pull request by thilo**
https://github.com/langalex/couch_potato

### CODE REVIEW

**Comment by wagenet** [comment]
Thanks! I'm out of town most of this week, but I'll try to give this a review soon.

**Comment by wagenet** [comment]
(NOTE: CLA has been signed 👍 )

**Comment by thilo** [comment]
Hi, any update on that?

**Comment by wagenet** [comment]
@thilo merged! It will be in our next release. Alternatively, you can just point your Gemfile to GitHub to use the latest master.

**Comment by wagenet** [comment]
@thilo I'm looking at the source of couch_potato and I don't see any evidence of the `couch_potato.load` and `couch_potato.view` instrumentation. Does this actually work?

**Comment by wagenet** [comment]
@thilo I'm going to remove this unless you can verify that this actually works.

**Comment by thilo** [comment]
@wagenet ouch! Hi! Saw that was removed with 2.0.0 Sorry I didn't noticed you mentioning me on that. Yes it worked and was super helpful. We have not been using skylight for a while but just enabled it again and I found out about your comment by browsing the change log. The instrumentation has been added to couch_potato here: https://github.com/langalex/couch_potato/blob/additional-databases/lib/couch_potato/database.rb#L113 I will also see why the couch_potato releases have not been build from master (for quite some time actually).

**Comment by thilo** [comment]
Update on the releases for couch_potato. They are all build from the 1.x branch, master is for a future 2.x release but does not contain all additions to the 1.x branch.

**Comment by wagenet** [comment]
@thilo my apologies! I should have realized that it was built from a branch. I can bring it back for a future 3.x release.

**Comment by thilo** [comment]
@wagenet thank you that would be highly appreciated as this would help us immensely to identify the views that would benefit most from a migration to the new query language in couchdb 2.x.

**Comment by thilo** [comment]
Can I help in any way?

**Pull request merged**
